"""first revision

Revision ID: 315f1cd5b745
Revises: 
Create Date: 2023-08-25 18:15:27.080550

"""
from typing import Sequence, Union

from alembic import op
import fastapi_utils
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '315f1cd5b745'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_answers',
    sa.Column('id', fastapi_utils.guid_type.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=False),
    sa.Column('quest', sa.String(length=255), nullable=False),
    sa.Column('swift_air_speed', sa.Integer(), nullable=False),
    sa.Column('may_pass', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_answers')
    # ### end Alembic commands ###
