"""added created and updated

Revision ID: f5a8d541020f
Revises: 315f1cd5b745
Create Date: 2023-08-25 18:20:21.980925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a8d541020f'
down_revision: Union[str, None] = '315f1cd5b745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_answers', sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('form_answers', sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_answers', 'updatedAt')
    op.drop_column('form_answers', 'createdAt')
    # ### end Alembic commands ###
